// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  image_bolck: dynamic(() => import("./ImageBolck")),
  techlist: dynamic(() => import("./Techlist")),
  text_block: dynamic(() => import("./TextBlock")),
};
